### ISSUE TITLE
Fatal error: Uncaught Error

### ISSUE THREAD

**Issue by bboy11501** [zao-web/stripe-connect-for-woocommerce#1]
Every time I upload and activate I get this error:
Fatal error: Uncaught Error: Class 'WC_Stripe_API' not found in /homepages/20/d861329070/htdocs/clickandbuilds/DynastyCollectingMarketplace/wp-content/plugins/stripe-connect-for-woocommerce-master/includes/settings.php:8 Stack trace: #0 /homepages/20/d861329070/htdocs/clickandbuilds/DynastyCollectingMarketplace/wp-content/plugins/stripe-connect-for-woocommerce-master/stripe-connect-for-woocommerce.php(143): include_once() #1 /homepages/20/d861329070/htdocs/clickandbuilds/DynastyCollectingMarketplace/wp-content/plugins/stripe-connect-for-woocommerce-master/stripe-connect-for-woocommerce.php(1060): Stripe_Connect_For_WooCommerce->plugin_classes() #2 /homepages/20/d861329070/htdocs/clickandbuilds/DynastyCollectingMarketplace/wp-includes/class-wp-hook.php(292): Stripe_Connect_For_WooCommerce->init('') #3 /homepages/20/d861329070/htdocs/clickandbuilds/DynastyCollectingMarketplace/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters(NULL, Array) #4 /homepages/20/d861329070/htdocs/clickandbuilds/DynastyCollectingMarketplac in /homepages/20/d861329070/htdocs/clickandbuilds/DynastyCollectingMarketplace/wp-content/plugins/stripe-connect-for-woocommerce-master/includes/settings.php on line 8
There has been a critical error on this website. Please check your site admin email inbox for instructions.

**Comment by JustinSainton** [comment]
Howdy!

The first thing I'd check here is to confirm that you have the WooCommerce Stripe plugin/gateway activated. That should have the WC_Stripe_API calss.
